# Generated by Django 4.0.4 on 2022-04-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='type_food',
            field=models.CharField(choices=[('drink', 'نوشیدنی'), ('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام')], default='breakfast', max_length=10, verbose_name='نوع غذا'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='photo',
            field=models.ImageField(upload_to='image/', verbose_name='عکس'),
        ),
    ]
