# Generated by Django 4.0.4 on 2022-04-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی ')),
                ('email', models.EmailField(max_length=50, verbose_name='نام و نام خانوادگی ')),
                ('phone', models.CharField(max_length=13, verbose_name='نام و نام خانوادگی ')),
                ('date', models.DateField(verbose_name='نام و نام خانوادگی ')),
                ('time', models.TimeField(verbose_name='نام و نام خانوادگی ')),
                ('person', models.IntegerField(default=0, verbose_name='تعداد ')),
            ],
        ),
    ]
