# Generated by Django 4.0.4 on 2022-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='date',
            field=models.DateField(verbose_name='تاریخ '),
        ),
        migrations.AlterField(
            model_name='reserv',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='پست الکترونیکی '),
        ),
        migrations.AlterField(
            model_name='reserv',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='تلفن همراه '),
        ),
        migrations.AlterField(
            model_name='reserv',
            name='time',
            field=models.TimeField(verbose_name='ساعت '),
        ),
    ]
