# Generated by Django 4.0.4 on 2022-04-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reserv_date_alter_reserv_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserv',
            name='person',
        ),
        migrations.RemoveField(
            model_name='reserv',
            name='time',
        ),
    ]
