# Generated by Django 4.0.4 on 2022-04-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reserv_person_remove_reserv_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='person',
            field=models.IntegerField(default=0, null=True, verbose_name='تعداد '),
        ),
        migrations.AddField(
            model_name='reserv',
            name='time',
            field=models.TimeField(null=True, verbose_name='ساعت '),
        ),
    ]
